name: ashes
description: "Semester 6 Project, Ashes Sports Team App"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  url_launcher: ^6.2.4
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  google_sign_in: ^6.2.1
  http: any
  cloud_firestore: ^4.15.9
  intl: ^0.19.0
#  sign_in_button: ^3.2.0
#  animated_splash_screen: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
     - images/
  fonts:
    - family: malayalam
      fonts:
        - asset: assets/fonts/malayalam.ttf

#    - family: outline
#      fonts:
#        - asset: assets/fonts/outline.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic

