
// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// ignore: depend_on_referenced_packages
import "package:firebase_core/firebase_core.dart" show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRN8B9hj89R1Zghjj64plxAfRn3rIlhKM',
    appId: '1:415546642092:android:10a6df27d9d6a351ca9909',
    messagingSenderId: '415546642092',
    projectId: 'ashes-3d1a1',
    storageBucket: 'ashes-3d1a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQ5WqU8GAhX1wGfuuIjpZrvuztFVbTCHg',
    appId: '1:415546642092:ios:579c861e6b9bb6daca9909',
    messagingSenderId: '415546642092',
    projectId: 'ashes-3d1a1',
    storageBucket: 'ashes-3d1a1.appspot.com',
    iosBundleId: 'com.example.ashes',
  );
}
const firebaseConfig = {
"project_info": {
"project_number": "415546642092",
"project_id": "ashes-3d1a1",
"storage_bucket": "ashes-3d1a1.appspot.com"
},
"client": [
{
"client_info": {
"mobilesdk_app_id": "1:415546642092:android:10a6df27d9d6a351ca9909",
"android_client_info": {
"package_name": "com.example.ashes"
}
},
"oauth_client": [
{
"client_id": "415546642092-im6dup1tob3ihmannbogijskno6fej96.apps.googleusercontent.com",
"client_type": 1,
"android_info": {
"package_name": "com.example.ashes",
"certificate_hash": "fb78b309286d23b7676040401d590ce7da7d3a54"
}
},
{
"client_id": "415546642092-qble9jd53oedgsngeu5nb4og4qr2qvu9.apps.googleusercontent.com",
"client_type": 3
}
],
"api_key": [
{
"current_key": "AIzaSyBRN8B9hj89R1Zghjj64plxAfRn3rIlhKM"
}
],
"services": {
"appinvite_service": {
"other_platform_oauth_client": [
{
"client_id": "415546642092-qble9jd53oedgsngeu5nb4og4qr2qvu9.apps.googleusercontent.com",
"client_type": 3
},
{
"client_id": "415546642092-d2ialflqglqnedee4jolh6im3u7j00lv.apps.googleusercontent.com",
"client_type": 2,
"ios_info": {
"bundle_id": "com.example.ashes"
}
}
]
}
}
}
],
"configuration_version": "1"
};
